DP-781 contact us failed to send flash message.
cabinetoffice/GCGS-Central-Digital-Platform pull request #1011
Opened 2024-12-03 14:34 UTC by dbgoaco

[DP-781](https://noticingsystem.atlassian.net/jira/software/projects/DP/boards/22?selectedIssue=DP-781&text=DP-781)

2024-12-03 15:07 UTC, andymantell requested changes

2024-12-03 15:07 UTC, andymantell commented on Frontend/CO.CDP.OrganisationApp/Pages/Shared/_FlashMessage.cshtml
> +                    @:Failure
This word "Failure" here needs localizing

2024-12-03 15:07 UTC, andymantell commented on Frontend/CO.CDP.OrganisationApp/Pages/Shared/_FlashMessage.cshtml
> +                    @:Failure
You could consider making `Supplementary_ContactUs_Failure_Heading` into `Global_Failure_Heading` and just using it here

2024-12-03 15:47 UTC, andymantell approved these changes

2024-12-05 09:40 UTC, dharmverma approved these changes

2024-12-05 09:41 UTC, merged