Feature/dp 998 user management translations
cabinetoffice/GCGS-Central-Digital-Platform pull request #1058
Opened 2024-12-12 16:42 UTC by rmohammed-goaco

2024-12-13 16:11 UTC, JBaigGoaco approved these changes

2024-12-13 16:13 UTC, maciej-goaco approved these changes

2024-12-16 08:12 UTC, andymantell requested changes

2024-12-16 08:12 UTC, andymantell commented on Frontend/CO.CDP.OrganisationApp/Pages/Users/AddUser.cshtml
> +                            <span class="govuk-visually-hidden">@StaticTextResource.Global_ErrorColon</span>
Can this be consistent with the other forms - This should be as follows, and we can remove the ErrorColon version 

```suggestion
                            <span class="govuk-visually-hidden">@StaticTextResource.Global_Error:</span>
```

2024-12-16 08:12 UTC, andymantell commented on Services/CO.CDP.Localization/StaticTextResource.resx
> +  </data>
As above, we have `GlobalError` already

2024-12-17 08:15 UTC, andymantell approved these changes

2024-12-18 15:09 UTC, merged