DP-222: make other services use serilog
cabinetoffice/GCGS-Central-Digital-Platform pull request #570
Opened 2024-09-05 15:04 UTC by mareg

2024-09-05 20:56 UTC, jakzal commented on Libraries/CO.CDP.AwsServices/AwsConfiguration.cs
> +    public string? LogStream { get; init; }
Since we grouped these two under CloudWatch, we can make these non-nullable (CloudWatch above in AwsCredentials remains nullable).

2024-09-05 20:59 UTC, jakzal commented on Libraries/CO.CDP.AwsServices/CloudWatchExtensions.cs
> +                LogGroupName = awsConfiguration.CloudWatch.LogGroup,
Once LogGroup is made required non-null, `awsConfiguration?.CloudWatch.LogGroup`

2024-09-06 10:50 UTC, jakzal requested changes
Static analysis warnings need to be fixed

2024-09-06 11:18 UTC, mareg commented
> Static analysis warnings need to be fixed

They are fixed now :+1:

2024-09-06 12:46 UTC, jakzal approved these changes

2024-09-06 12:48 UTC, merged