Feature/dp 660 apply sorting on form answers
cabinetoffice/GCGS-Central-Digital-Platform pull request #709
Opened 2024-10-03 14:46 UTC by shilpigoel-goaco

2024-10-03 14:57 UTC, andymantell requested changes

2024-10-03 14:57 UTC, andymantell commented on Services/CO.CDP.OrganisationInformation.Persistence/Migrations/20241003131026_QuestionSortOrder.cs
> +                    UPDATE form_questions SET sort_order = 1 WHERE name='_Exclusion07';
Some exclusion questions are missing. This is the full set. You may need to update from main and run your local migrations to get all the new ones.
![image](https://github.com/user-attachments/assets/5442f97e-42c7-4e88-8526-4e5c716bb181)

2024-10-03 15:24 UTC, andymantell approved these changes

2024-10-03 17:02 UTC, dharmverma approved these changes

2024-10-04 07:42 UTC, JBaigGoaco approved these changes

2024-10-04 08:20 UTC, merged