DP-741 - Migration added
cabinetoffice/GCGS-Central-Digital-Platform pull request #888
Opened 2024-11-01 16:46 UTC by maciej-goaco

2024-11-01 16:48 UTC, andymantell submitted a review, later dismissed

2024-11-04 08:50 UTC, andymantell requested changes
```Npgsql.PostgresException : 42P13: cannot change return type of existing function```

Looks like replacing it won't work. Can you remove the function and re-add it?

2024-11-04 09:23 UTC, andymantell approved these changes

2024-11-04 11:08 UTC, jakzal approved these changes

2024-11-04 11:09 UTC, merged